(define (average_pairs lst)
    (let ((retn) (looper))
        (set! retn ())
        (define (looper i)
            (set! a (nth i lst))
            (if (< i (- (length lst) 2) )
                (set! b (nth (+ i 2) lst))
                (set! b (- a 20))
            )
            (set! b (/  (+ a b) 2))
            (set! retn (append retn (list a b)))
            (format t "%d %d\n" a b)
            (set! i (+ i 2))
            (if (< i (length lst)) (looper i))
        )
        (looper 0)
        retn
    )
)

(set! a (list 200 300 400 500))
(print (average_pairs a))
(print retn)
